### ISSUE TITLE
Feature request: Remove dependency on proprietary libVA fork

### ISSUE THREAD

**Issue by vanvugt** [Intel-Media-SDK/MediaSDK#10]
According to the readme:
"Intel Media SDK depends on a special version of LibVA which comes with Intel Media Server Studio installation and is not in upstream, so this version is not compatible with the LibVA/driver available at 01org."

So building this open source project is not yet possible with a purely open source environment (public upstream VA-API). It would be very helpful to desktop Linux distributions if future versions of MSDK could build without any proprietary downloads from intel.com. Just depend on upstream libVA, at least as an option.

**Comment by onabiull** [comment]
Compatibility with public upstream LibVA definitely on our radar. I can't give any strong commitments, but you may expect that MediaSDK will be compatible with opensource LibVA at some point in future.

**Comment by onabiull** [comment]
Could we close this one?

**Comment by vanvugt** [comment]
I don't think so, unless it has been fixed?

**Comment by onabiull** [comment]
Latest master depends on opensource LibVA: [https://github.com/01org/libva/commit/df544cd5a31e54d4cbd33a391795a8747ddaf789](url), so I guess yes, it is fixed :)

**Comment by vanvugt** [comment]
Sounds good, but commit df544cd5a31e54d4cbd33a391795a8747ddaf789 does not appear to be related to this issue.

Is it fixed by some different commit?

**Comment by onabiull** [comment]
It fixed in Media SDK commits [1340575fffa](https://github.com/Intel-Media-SDK/MediaSDK/commit/1340575fffa39ba0ff1f58ed762f7d6fde672f9c) and [934c36b9d0f](https://github.com/Intel-Media-SDK/MediaSDK/commit/934c36b9d0f01af04de23c35d63b5916ee7b3102). Essentially we switched from proprietary LibVA to publicly-available LibVA 2.1. Moreover appropriate LibVA user mode driver also became open source, see [https://github.com/intel/media-driver](url).

**Comment by vanvugt** [comment]
That sounds right. Yes, sounds closed.
