### ISSUE TITLE
Look ahead is not support on KBL

### ISSUE THREAD

**Issue by lizhong1008** [Intel-Media-SDK/MediaSDK#1046]
Looks like look_ahead mode can't be support by KBL (but can support on SKL).
Would you please consider expose this limitaion in MFXVideoENCODE_Query() or support it on KBL+ platform?

>ffmpeg -hwaccel qsv -c:v h264_qsv -i /root/Videos/bbb_sunflower_1080p_30fps_normal.mp4 -c:v h264_qsv -b:v 5M -look_ahead 1 output.mp4 -v verbose -y
ffmpeg version N-92731-g5c981ef745 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
  configuration: --enable-libmfx --enable-libx264 --enable-gpl --disable-optimizations --enable-debug=3 --enable-vaapi --enable-sdl
  libavutil      56. 24.101 / 56. 24.101
  libavcodec     58. 42.103 / 58. 42.103
  libavformat    58. 24.101 / 58. 24.101
  libavdevice    58.  6.101 / 58.  6.101
  libavfilter     7. 46.101 /  7. 46.101
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
[h264 @ 0x558c95c024c0] Reinit context to 1920x1088, pix_fmt: yuv420p
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/root/Videos/bbb_sunflower_1080p_30fps_normal.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1
    creation_time   : 2013-12-16T17:44:39.000000Z
    title           : Big Buck Bunny, Sunflower version
    artist          : Blender Foundation 2008, Janus Bager Kristensen 2013
    comment         : Creative Commons Attribution 3.0 - http://bbb3d.renderfarming.net
    genre           : Animation
    composer        : Sacha Goedegebure
  Duration: 00:10:34.53, start: 0.000000, bitrate: 3481 kb/s
    Stream #0:0(und): Video: h264 (High), 1 reference frame (avc1 / 0x31637661), yuv420p(left), 1920x1080 (1920x1088) [SAR 1:1 DAR 16:9], 2998 kb/s, 30 fps, 30 tbr, 30k tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2013-12-16T17:44:39.000000Z
      handler_name    : GPAC ISO Video Handler
    Stream #0:1(und): Audio: mp3 (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 160 kb/s (default)
    Metadata:
      creation_time   : 2013-12-16T17:44:42.000000Z
      handler_name    : GPAC ISO Audio Handler
    Stream #0:2(und): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, 5.1(side), fltp, 320 kb/s (default)
    Metadata:
      creation_time   : 2013-12-16T17:44:42.000000Z
      handler_name    : GPAC ISO Audio Handler
    Side data:
      audio service type: main
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_qsv) -> h264 (h264_qsv))
  Stream #0:2 -> #0:1 (ac3 (native) -> aac (native))
Press [q] to stop, [?] for help
[AVHWDeviceContext @ 0x558c95c3e240] Opened VA display via X11 display :0.0.
[AVHWDeviceContext @ 0x558c95c3e240] libva: VA-API version 1.4.0
[AVHWDeviceContext @ 0x558c95c3e240] libva: va_getDriverName() returns 0
[AVHWDeviceContext @ 0x558c95c3e240] libva: User requested driver 'iHD'
[AVHWDeviceContext @ 0x558c95c3e240] libva: Trying to open /opt/mdsk_opensource/vaapi/lib/dri/iHD_drv_video.so
[AVHWDeviceContext @ 0x558c95c3e240] libva: Found init function __vaDriverInit_1_4
[AVHWDeviceContext @ 0x558c95c3e240] libva: va_openDriver() returns 0
[AVHWDeviceContext @ 0x558c95c3e240] Initialised VAAPI connection: version 1.4
[AVHWDeviceContext @ 0x558c95c3e240] VAAPI driver: Intel iHD driver - 1.0.0.
[AVHWDeviceContext @ 0x558c95c3e240] Driver not found in known nonstandard list, using standard behaviour.
[AVHWDeviceContext @ 0x558c95c2e540] Initialize MFX session: API version is 1.28, implementation version is 1.28
[AVHWDeviceContext @ 0x558c95c2e540] MFX compile/runtime API: 1.28/1.28
[AVHWDeviceContext @ 0x558c95dc64c0] VAAPI driver: Intel iHD driver - 1.0.0.
[AVHWDeviceContext @ 0x558c95dc64c0] Driver not found in known nonstandard list, using standard behaviour.
[graph 0 input from stream 0:0 @ 0x558c95e2ba80] w:1920 h:1080 pixfmt:qsv tb:1/30000 fr:30/1 sar:1/1 sws_param:flags=2
[h264_qsv @ 0x558c95c2ff00] Using the VBR with lookahead (LA) ratecontrol method
[h264_qsv @ 0x558c95c2ff00] MFMode:2
[AVHWDeviceContext @ 0x558c95cd1bc0] VAAPI driver: Intel iHD driver - 1.0.0.
[AVHWDeviceContext @ 0x558c95cd1bc0] Driver not found in known nonstandard list, using standard behaviour.
[AVHWDeviceContext @ 0x558c962a9900] VAAPI driver: Intel iHD driver - 1.0.0.
[AVHWDeviceContext @ 0x558c962a9900] Driver not found in known nonstandard list, using standard behaviour.
[h264_qsv @ 0x558c95c2ff00] Error initializing the encoder: unsupported (-3)
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[AVIOContext @ 0x558c95c23140] Statistics: 0 seeks, 0 writeouts
[AVIOContext @ 0x558c95c09480] Statistics: 350943 bytes read, 2 seeks
Conversion failed!

**Comment by onabiull** [comment]
In our validation lookahead work consistently on KBL and CFL with results aligned with SKL. I suppose some kind of configuration/installation problem. Could you please post a device ID?

**Comment by jstebbins** [comment]
I may be experiencing the same issue.  I'm using HandBrake as a frontend rather than ffmpeg, but symptoms are similar.  Enable lookahead, it fails to initialize. KBL CPU

Device ID 0x591B (i7-7700HQ)

gdb backtrace when error occurs
~~~
(gdb) bt
#0  0x00007ffff5e6f53f in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff5e59895 in __GI_abort () at abort.c:79
#2  0x00007ffff5e59769 in __assert_fail_base
    (fmt=0x7ffff5fc0e90 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7fffce711714 "!\"CmRuntimeError\"", file=0x7fffce7116b8 "/home/jstebbins/Source/MediaSDK/_studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_cm.h", line=65, function=<optimized out>) at assert.c:92
#3  0x00007ffff5e679f6 in __GI___assert_fail
    (assertion=0x7fffce711714 "!\"CmRuntimeError\"", file=0x7fffce7116b8 "/home/jstebbins/Source/MediaSDK/_studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_cm.h", line=65, function=0x7fffce711e00 <MfxHwH264Encode::CmRuntimeError::CmRuntimeError()::__PRETTY_FUNCTION__> "MfxHwH264Encode::CmRuntimeError::CmRuntimeError()") at assert.c:101
#4  0x00007fffce57e8ad in MfxHwH264Encode::CmRuntimeError::CmRuntimeError()
    (this=0x7fffc8007910)
    at /home/jstebbins/Source/MediaSDK/_studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_cm.h:65
#5  0x00007fffce609b26 in MfxHwH264Encode::CmContext::Setup(MfxHwH264Encode::MfxVideoParam const&, CmDevice*, VideoCORE*) (this=0x7fffc8b42b50, video=..., 
    cmDevice=0x7fffc80e0740, core=0x7fffc80b4670)
    at /home/jstebbins/Source/MediaSDK/_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_cm.cpp:848
#6  0x00007fffce6098d7 in MfxHwH264Encode::CmContext::CmContext(MfxHwH264Encode::MfxVideoParam const&, CmDevice*, VideoCORE*)
    (this=0x7fffc8b42b50, video=..., cmDevice=0x7fffc80e0740, core=0x7fffc80b4670)
    at /home/jstebbins/Source/MediaSDK/_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_cm.cpp:831
#7  0x00007fffce570c8f in MfxHwH264Encode::ImplementationAvc::Init(mfxVideoParam*) (this=0x7fffc8103f40, par=0x7fffc80b0010)
    at /home/jstebbins/Source/MediaSDK/_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp:1049
#8  0x00007fffce56d214 in MFXHWVideoENCODEH264::Init(mfxVideoParam*)
    (this=0x7fffc80e0970, par=0x7fffc80b0010)
    at /home/jstebbins/Source/MediaSDK/_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp:188
#9  0x00007fffce316f65 in MFXVideoENCODE_Init(mfxSession, mfxVideoParam*) (
    session=0x7fffc80b4498, par=0x7fffc80b0010)
    at /home/jstebbins/Source/MediaSDK/_studio/mfx_lib/shared/src/libmfxsw_encode.cpp:707
#10 0x00000000027fa63f in MFXVideoENCODE_Init(mfxSession, mfxVideoParam*)
--Type <RET> for more, q to quit, c to continue without paging--
    (session=0x7fffc80b4498, par=0x7fffc80b0010)
    at src/mfx_exposed_functions_list.h:62
#11 0x00000000004bc66a in encqsvInit (w=0x7fffc8006110, job=0x7fffc80235d0)
    at ../libhb/enc_qsv.c:1118
#12 0x00000000004a7e44 in do_job (job=0x7fffc80235d0) at ../libhb/work.c:1758
#13 0x00000000004a491b in work_func (_work=0x4678130) at ../libhb/work.c:154
#14 0x000000000046f829 in hb_thread_func (_t=0x5619180) at ../libhb/ports.c:870
#15 0x00007ffff73fa58e in start_thread (arg=<optimized out>)
    at pthread_create.c:486
#16 0x00007ffff5f346a3 in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
~~~

**Comment by jstebbins** [comment]
So, I've figured out my particular problem after reproducing this in various ways.  It turns out there are several ways to misconfigure things and get the same symptoms. And at least one way to configure things that really ought to work, but doesn't :wink:

My goal was to produce a flatpak plugin with a clean set of compatible components. The flatpak plugin built correctly and actually contains all compatible components, *but* I used the "MSS KBL 2019 R1" release from https://github.com/VCDP/media-driver (basically the top release on the releases page with some corrections since it doesn't actually build with the listed dependencies https://github.com/Intel-Media-SDK/MediaSDK/releases).  This branch produces an unversioned igfxcmrt64.so.  The flatpak environment sets up ld.so.cache correctly to find shared objects associated with the plugin, but the unversioned lib doesn't get cached, so is not found when the application is run. Pulling in the commit that added versioning to this lib *and* using a MediaSDK version that dlopens with the new libigfxcmrt64.so name fixes this particular glitch.

I was also trying to debug this outside the flatpak sandbox.  Various configuration errors resulted in the same symptoms.  So double and triple check configuration :wink"

I also tried the next release down in the list after figuring out the root cause(s) of my problem. It worked without issue.  It appears to announce the same capabilities as the MSS KBL release when queried.  So now I'm wondering, what distinguishes these releases.  The release notes of MSS KBL list several new features, but it appears that 18.4.1 advertises it has these features as well.

**Comment by onabiull** [comment]
Media Server Studio releases validated against patched version of i915 KMD which published at https://github.com/VCDP/linux-kmd/ on a limited set of platforms comparing to quarterly releases. Release "MSS KBL 2019 R1" are essentially 18.3**.2** which validated on patched 4.19 and only on KBL platform.

**Comment by jstebbins** [comment]
Good to know, thanks.  This is working great now on linux in a flatpak sandbox using 18.4.1.

**Comment by lizhong1008** [comment]
Verified it can work now
