### ISSUE TITLE
[KBL] FFmpeg QSV initialization fails on HadesCanyon (which has both Intel & AMD GPUs)

### ISSUE THREAD

**Issue by eero-t** [Intel-Media-SDK/MediaSDK#1067]
Setup:
* Ubuntu 18.04
* KBL HadesCanyon (i7-8809G, GT2)
* Latest FFmpeg, MediaSDK, libva, intel-driver and gmmlib built from git
* drm-git kernel v4.19 or v4.20-rc

Test-case:
* FFmpeg transcoding with QSV, for example:
`ffmpeg -hwaccel qsv -c:v mpeg2_qsv -i 1920x1080i_29.97_20mb_mpeg2_high.mpv -c:v h264_qsv -b:v 6M 0024_HD17i7_1.0.h264`

Actual outcome:
```
...
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg2video (mpeg2_qsv) -> h264 (h264_qsv))
Press [q] to stop, [?] for help
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [2]
param: 4, val: 0
[AVHWDeviceContext @ 0x55a0ad0ee600] Failed to initialise VAAPI connection: 1 (operation failed).
Error creating a QSV device
qsv hwaccel requested for input stream #0:0, but cannot be initialized.
Error while decoding stream #0:0: Operation not permitted
[mpeg2_qsv @ 0x55a0ad0f8e80] video_get_buffer: image parameters invalid
[mpeg2_qsv @ 0x55a0ad0f8e80] get_buffer() failed
Error while decoding stream #0:0: Invalid argument
[mpeg2_qsv @ 0x55a0ad0f8e80] video_get_buffer: image parameters invalid
[mpeg2_qsv @ 0x55a0ad0f8e80] get_buffer() failed
...
[mpeg2_qsv @ 0x55a0ad0f8e80] Too many errors when draining, this is a bug. Stop draining and force EOF.
Error while decoding stream #0:0: Internal bug, should not have happened
[h264_qsv @ 0x55a0ad0fa2c0] Selected ratecontrol mode is unsupported
[h264_qsv @ 0x55a0ad0fa2c0] Current frame rate is unsupported
[h264_qsv @ 0x55a0ad0fa2c0] Current picture structure is unsupported
[h264_qsv @ 0x55a0ad0fa2c0] Current resolution is unsupported
[h264_qsv @ 0x55a0ad0fa2c0] Current pixel format is unsupported
[h264_qsv @ 0x55a0ad0fa2c0] some encoding parameters are not supported by the QSV runtime. Please double check the input parameters.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```

It's expected to work, because it works:
* on other KBL devices (GT2, GT3e)
* using FFmpeg with VA-API acceleration instead of QSV with same drivers
* using MediaSDK sample transcode application to do the same thing

"lspci" says following for this device:
```
00:02.0 Display controller: Intel Corporation HD Graphics 630 (rev 04)
...
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Vega [Radeon RX Vega M] (rev c0)
```

**Comment by uartie** [comment]
Have you tried using `-hwaccel_device /dev/dri/renderD128` option?  NOTE: the intel device might be named `/dev/dri/renderD129` on your system.

**Comment by eero-t** [comment]
Tried it now, and that doesn't help.

However, I accidentally found out that unsetting "DISPLAY" gets things working...

Why MediaSDK, or its FFmpeg QSV wrapper, would care about X?  X server is using AMD driver to drive AMD VEGA chip.

**Comment by dvrogozh** [comment]
I think that 2 things could go wrong:
1. mediasdk library failed to detected what kind of Intel GPU is in use, this is happening here https://github.com/Intel-Media-SDK/MediaSDK/blob/master/_studio/shared/src/libmfx_core_vaapi.cpp#L320 thru the DRM_IOCTL_I915_GETPARAM
2. Other than 1) mediasdk _library_ does not care about X, Wayland, etc. at all. The trick is that it is user responsibility to initialize LibVA and pass valid VADisplay into mediasdk library.

I very much think that 1) is unlikely to be a problem. Without having the system to try I think we step into 2) where application/user does something wrong. This could be ffmpeg or libva itself.

Actually, I think that I remember the following code sequence in libva-drm backend tended to do the following:
1. Try to open VADisplay _thru_ the X if DISPLAY presents
2. Try to _really_ open VADisplay thru DRM

I think this was the case very long ago when we did not have render nodes and code could change. But I would not be surprised if code did _not_ change since headless mode is a pretty corner use case sometimes with specific systems configurations. LibVA code around drm is here: https://github.com/intel/libva/blob/master/va/drm/va_drm.c.

**Comment by eero-t** [comment]
Gdb breakpoints on "va_drm_authenticate" & "va_drm_authenticate_x11" don't trigger.

From strace output I can see following files to have been opened, without DISPLAY:
```
...
<input video>
<output video>
/dev/dri/renderD128
/path/to/iHD_drv_video.so
```

Whereas with DISPLAY set, following are opened instead:
```
...
<input video>
<output video>
/home/user/.Xauthority
/dev/dri/card1
/path/to/iHD_drv_video.so
```
Before this, the list of opened files / libraries was identical.  E.g.  "libva-x11.so" was loaded by both already before, but not by dlopen(), like would happen if drm_auth_x11_init() would have been called.

When using "latrace" to trace library calls, without DISPLAY I see following:
```
...
XOpenDisplay(nil)
XDisplayName(0, , , 4720)
vaGetDisplayDRM(5, , 2, 0)
vaSetErrorCallback(, , , )
vaSetInfoCallback(, , , )
vaInitialize(, , , ) = 0
```

Whereas with DISPLAY set, it goes:
```
...
XOpenDisplay(nil)
vaGetDisplay(, 85, , 0)
XDisplayName(0, 0, , )
vaSetErrorCallback(, , , )
vaSetInfoCallback(, , , )
vaInitialize(, , , ) = 1
```

**Comment by eero-t** [comment]
Above differences actually seem to come from "vaapi_device_create" in FFmpeg:
https://github.com/FFmpeg/FFmpeg/blob/master/libavutil/hwcontext_vaapi.c#L1482

**Comment by eero-t** [comment]
Reported to upstream FFmpeg: https://trac.ffmpeg.org/ticket/7649

**Comment by dvrogozh** [comment]
@eero-t : I afraid that the scenario which I have described will be the second level issue once ffmpeg behavior will be addressed. @lizhong1008 : can you, please, help with https://trac.ffmpeg.org/ticket/7649 and pay attention that we anticipate 2nd level issue on LibVA level once ffmpeg will be solved.

**Comment by lizhong1008** [comment]
In ffmpeg level, vaapi_device_create() in  https://github.com/FFmpeg/FFmpeg/blob/master/libavutil/hwcontext_vaapi.c#L1467 is a common function for both ffmpeg-vaapi and ffmpeg-qsv.  I think HAVE_VAAPI_DRM should be high priority than HAVE_VAAPI_X11, and then this issue can be fixed.

However, I noted ffmpeg-vaapi can work well with setting hwaccel_device  /dev/dri/renderD128, but ffmpeg-qsv failed, thus due to in https://github.com/FFmpeg/FFmpeg/blob/master/libavutil/hwcontext_qsv.c#L1232，hwaccel_device  is ignored and always set to be NULL, thus should be an issue should be fixed.

**Comment by lizhong1008** [comment]
Please see my comment in https://trac.ffmpeg.org/ticket/7649?replyto=2#comment:2

**Comment by eero-t** [comment]
This use-case works fine if correct render node is given with -qsv_device option, similar to how one needs to use -vaapi_device with VA-API, so from my point of view this can be closed.

I think the underlying libs should still be fixed though.

**Comment by lizhong1008** [comment]
@eero-t , could you please take a look that whether vainfo can work well for you if no X display started up (I afraid it can't work well  due to the default drm device can't be initialized successfully)? if not, it is recommended to create a issue to libva project.

**Comment by eero-t** [comment]
It does work:
```
$ LIBVA_DRIVER_NAME=iHD vainfo
error: can't connect to X server!
libva info: VA-API version 1.5.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /path/to/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_5
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.5 (libva 2.1.0)
vainfo: Driver version: Intel iHD driver - 1.0.0
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
...
```
Upstream FFmpeg ticket I filed, was just closed without actually anything being fixed.  The main issue is that the need to use  "-qsv_device" option with FFmpeg still isn't documented anywhere (no example command lines use it etc).

**Comment by lizhong1008** [comment]
@eero-t , thanks for your info.  Now “-qsv_device” has been documented now

**Comment by daleksan** [comment]
@eero-t is it still actual?

**Comment by eero-t** [comment]
This seems to have been fixed in the driver. I don't anymore need to give -qsv_device (or -vaapi_device for VA-API) even on HadesCanyon -> FIXED
