### ISSUE TITLE
[KBL][Jpeg dec] sample_decode jpeg fail on KBL but pass on SKL.

### ISSUE THREAD

**Issue by feiwan1** [Intel-Media-SDK/MediaSDK#1073]
Same cmdline works on SKL, but fail on KBL.
$ sample_decode jpeg -i smpte_444P.jpeg -o a.yuv
[smpte_444P.jpeg.zip.zip](https://github.com/Intel-Media-SDK/MediaSDK/files/2720196/smpte_444P.jpeg.zip.zip)

**Comment by ekislyuk** [comment]
Hi! I've tried to reproduce fail on our KBL with latest MSDK/ media-driver from master: and could not reproduce it;  
If this problem is still actual for you - could you please provide more details- which msdk /driver version do you observe your system fails on? How exactly does it fail? could you please provide a log or  environment ?
