### ISSUE TITLE
Not generating makefile for libmfxsw?

### ISSUE THREAD

**Issue by coxuintel** [Intel-Media-SDK/MediaSDK#1230]
mfxloader LoaderCtx::Init() still load libmfxsw32/libmfxsw64 if specify MFX_IMPL_SOFTWARE in mfxInitParam. i.e. in sample_decode, add -sw to parameters.
However it seem like mfxsw is not added to build target in "MediaSDK/_studio/mfx_lib/CMakeLists.txt".

How to build libmfxsw32/libmfxsw64 so that I can use "-sw" in sample_decode/sample_encode?

cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_X11_DRI3=ON -DENABLE_WAYLAND=ON -DENABLE_STAT=ON -DBUILD_RUNTIME=ON -DBUILD_DISPATCHER=ON -DBUILD_SAMPLES=ON -DBUILD_TESTS=ON -DBUILD_TOOLS=ON ..

**Comment by onabiull** [comment]
Unfortunately this is expected. We have no plans to add sw-only library. Current project focus on hw feature enabling. Btw, since MSS 2018 R2 there no SW library in Media Server Studio Community Edition. It didn't gained wide enough adoption to justify further development and used to lag behind HW library from feature perspective.

**Comment by artem-shaporenko** [comment]
Hi @coxuintel, are you looking for software implementation support?

**Comment by coxuintel** [comment]
Emmm that make sense since sw library can’t benefit from HW acceleration which are expected to be the main purpose of MediaSDK.
I’m not looking for SW implementation support. Recently we are upgrading our performance benchmarking suite, which contains some obsolete test cases using sw library can’t run, and found that recent MediaSDK releases doesn’t have sw library included so raise the question here.

Thanks for your explanation.

--
Best Regards,
Colin Xu
