### ISSUE TITLE
IPP should be split as a separate project

### ISSUE THREAD

**Issue by tjaalton** [Intel-Media-SDK/MediaSDK#1284]
contrib/ipp is merged to allow SW fallback, but in the perfect world it would be a separate library mediasdk would link to

**Comment by onabiull** [comment]
I afraid this would just confuse opensource community. Actually it is not IPP :) Code which we have in contrib/ipp contains very small subset of Intel IPP. IPP split into groups of functions called domains. Our code contains mostly Media domain functions (which not available as part of real IPP since 8.0 or probably even 7.0), and a few support functions from Core and Image processing domains. Moreover it miss certain optimization types comparing to its parent library.

**Comment by tjaalton** [comment]
Ok, that explanation satisfies me, I guess. Thanks!
