### ISSUE TITLE
Clarify required linux kernel patches

### ISSUE THREAD

**Issue by alex3d** [Intel-Media-SDK/MediaSDK#1466]
Should we use vanilla linux kernel 4.19 or apply patch https://github.com/VCDP/linux-kmd/commit/d5cc059043749162c76285ea2c608da57bed8094 from https://github.com/VCDP/linux-kmd/commits/4.19_intel_media_kbl_19.1.0? (currently we use only SKL but intended to use KBL/CFL in near future)

Previous release MSS 2018 R2 HF2 required a bunch of 50 patches over vanilla linux kernel 4.14, but MSDK 2019 Q1 doesn't mention these patches and requires Kernel 4.14 or later (4.19 or later is recommended)

**Comment by onabiull** [comment]
We have two types of releases: quarterly with broader platform scope targeting vanilla kernel. And
Media Server Studio releases which validated against patched version of i915 KMD which published at https://github.com/VCDP/linux-kmd/ on a limited set of platforms comparing to quarterly releases.
For 2019 Q1 validation was performed against vanilla kernel and I'd recommend to stick with it.

**Comment by alex3d** [comment]
Thanks for information. I thought MSS is finally rebranded to MSDK as was stated in last year press release but seems it is not true yet.
We intended to use MSDK 2019 Q1 + linux 4.19 for both SKL and KBL to reduce moving parts but it seems it is not good release for SKL (`suboptimal performance and quality in certain usages comparing to Media Server Studio on Broadwell and Skylake platforms` in the release notes)

What do you recommend for production use (non-FEI) in terms of realibility/performance/picture quality given that we could use any linux kernel with/without patches?

**Comment by dvrogozh** [comment]
Performance difference between MSDK and MSS significantly depends on the selected SKU and usage models. Let me try to give you some hints. The major patches over kernel which give MSS performance improvements are:
1. Dynamic VDBOX balancing. I.e. dynamic tasks orchestration from few independent workloads over 2 VDBOX engines. This means that SKU should have 2 VDBOX engines for this to take effect. On GT2 systems patch has no effect. Or if your usage models focus on the single workload running on the system this also might not be much relevant.
2. Slice shutdown. I.e. for the encoding it is better to power off some EU slices to achieve optimal performance. Again, this means that system should have more than 1 slice, hence patch takes effect with GT3 and GT4 SKUs, but for GT2 patch is doing nothing. Next, effect is limited to encoding only and lower the resolution - bigger effect. Specifically, on SD resolutions it is better to have just 1 slice since its resources are enough, for 720p and for some 1080 case typically 2 slices are good, for >=1080p 3 slices might give better performance. Anyhow, if encoding is not the bottle neck for your workloads or you focus on >=FHD cases, patch might not be needed as well.

A range of other patches were upstreamed and are actually available in 4.19.

I hope this helps.

**Comment by alex3d** [comment]
Thanks for detailed explanation.
So performance issues of MSDK 2019 Q1 on SKL should not affect us (we use only SKL GT2 with multiple simultaneous workloads)
Could you explain `suboptimal quality in certain usages` part of the release notes?
Currently we use simple non-FEI transcoding pipelines (without advanced encoding options), deinterlacing and RGBA+NV12 composition.

**Comment by alex3d** [comment]
We have successfully updated from MSS 2018 R1 (linux kernel 4.4+patches) to MSDK 2019 Q1 (linux kernel 4.19 vanilla)

FYI, here are our benchmark/test results on Skylake i3-6300:
- transcoding speed roughly the same (MSDK 2019 Q1 0-5% faster in different testcases)
- MSDK 2019 Q1 slightly degraded mpeg2 quality (average PSNR: 39.0->38.1, average SSIM: 14.2->13.5)
- h264 quality has not changed
