### ISSUE TITLE
[sample_vpp][qsv_vpp][rotate+mirror+w/h change] sample vpp has garbage

### ISSUE THREAD

**Issue by fulinjie** [Intel-Media-SDK/MediaSDK#1493]
MSDK can cope with  both mirror and rotate in one time when copying from video memory to sys memory.

When swap the width and height as the request for rotation 90, there will be garbage.

[CMDLINE]
./sample_vpp -sw 352 -sh 288 -scc i420 -dw 288 -dh 352 -dcc i420 -iopattern d3d_to_sys -i /home/linjiefu/data/sourceVideo/MOBILE_352x288_30_orig_01.yuv -o msdk.yuv -mirror 1 -rotate 90 -n 10

[Message]
[WARNING] D3D11 does not support YV12 and I420 surfaces. Input will be converted to NV12 by file reader.
libva info: VA-API version 1.5.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/local/lib/dri//iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_5
libva info: va_openDriver() returns 0
VPP PIPELINE: 
RESIZE 
VPP_ROTATION
MFX_EXTBUFF_VPP_MIRRORING
VPP PIPELINE: 
RESIZE 
VPP_ROTATION
MFX_EXTBUFF_VPP_MIRRORING
VPP PIPELINE: 
RESIZE 
VPP_ROTATION
MFX_EXTBUFF_VPP_MIRRORING
VPP PIPELINE: 
RESIZE 
VPP_ROTATION
MFX_EXTBUFF_VPP_MIRRORING
VPP PIPELINE: 
RESIZE 
VPP_ROTATION
MFX_EXTBUFF_VPP_MIRRORING
VPP PIPELINE: 
RESIZE 
VPP_ROTATION
MFX_EXTBUFF_VPP_MIRRORING
VPP PIPELINE: 
RESIZE 
VPP_ROTATION
MFX_EXTBUFF_VPP_MIRRORING
VPP PIPELINE: 
RESIZE 
VPP_ROTATION
MFX_EXTBUFF_VPP_MIRRORING
VPP PIPELINE: 
RESIZE 
VPP_ROTATION
MFX_EXTBUFF_VPP_MIRRORING
VPP PIPELINE: 
RESIZE 
VPP_ROTATION
MFX_EXTBUFF_VPP_MIRRORING
Input format	NV12
Resolution	352x288
Crop X,Y,W,H	0,0,352,288
Frame rate	30.00
PicStruct	progressive
Output format	NV12
Resolution	288x352
Crop X,Y,W,H	0,0,288,352
Frame rate	30.00
PicStruct	progressive

Video Enhancement Algorithms
Deinterlace	OFF
Signal info	OFF
Scaling		OFF
CromaSiting		OFF
Denoise		OFF
MCTF		OFF
ProcAmp		OFF
DetailEnh	OFF
GamutMapping 	OFF
ColorSaturation	OFF
ContrastEnh  	OFF
SkinToneEnh  	OFF
MVC mode    	OFF
ImgStab    	OFF

IOpattern type               	d3d_to_sys
Number of asynchronious tasks	1
Time stamps checking         	OFF
ROI checking                 	OFF

MediaSDK impl	hw
HW accelaration is enabled
MediaSDK ver	1.29
VPP started
pInSurf[nInStreamInd] = 158751712
else in  set MctfRTParams.
[MOS]:  CRITICAL - Mos_Specific_GetMemoryCompressionMode:5502: Invalid (nullptr) Pointer.
pInSurf[nInStreamInd] = 158751712
else in  set MctfRTParams.
[MOS]:  CRITICAL - Mos_Specific_GetMemoryCompressionMode:5502: Invalid (nullptr) Pointer.
pInSurf[nInStreamInd] = 158751712
else in  set MctfRTParams.
[MOS]:  CRITICAL - Mos_Specific_GetMemoryCompressionMode:5502: Invalid (nullptr) Pointer.
pInSurf[nInStreamInd] = 158751712
else in  set MctfRTParams.
[MOS]:  CRITICAL - Mos_Specific_GetMemoryCompressionMode:5502: Invalid (nullptr) Pointer.
pInSurf[nInStreamInd] = 158751712
else in  set MctfRTParams.
[MOS]:  CRITICAL - Mos_Specific_GetMemoryCompressionMode:5502: Invalid (nullptr) Pointer.
pInSurf[nInStreamInd] = 158751712
else in  set MctfRTParams.
[MOS]:  CRITICAL - Mos_Specific_GetMemoryCompressionMode:5502: Invalid (nullptr) Pointer.
pInSurf[nInStreamInd] = 158751712
else in  set MctfRTParams.
[MOS]:  CRITICAL - Mos_Specific_GetMemoryCompressionMode:5502: Invalid (nullptr) Pointer.
pInSurf[nInStreamInd] = 158751712
else in  set MctfRTParams.
[MOS]:  CRITICAL - Mos_Specific_GetMemoryCompressionMode:5502: Invalid (nullptr) Pointer.
pInSurf[nInStreamInd] = 158751712
else in  set MctfRTParams.
[MOS]:  CRITICAL - Mos_Specific_GetMemoryCompressionMode:5502: Invalid (nullptr) Pointer.
pInSurf[nInStreamInd] = 158751712
else in  set MctfRTParams.
[MOS]:  CRITICAL - Mos_Specific_GetMemoryCompressionMode:5502: Invalid (nullptr) Pointer.
Frame number: 10
VPP finished

Total frames 10 
Total time 0.03 sec 
Frames per second 351.580 fps 

Summary:
1. Only rotate 90 + w/h change, output file is fine.
2. Only mirror, output file is fine.
3. rotate 90 + w/h change + mirror, output file has garbage.
4. same issue occurs in ffmpeg_qsv vpp after applying the patch
https://github.com/intel-media-ci/ffmpeg/pull/54
ffmpeg -init_hw_device qsv=foo -filter_hw_device foo -v debug -f rawvideo -pix_fmt yuv420p -s:v 352x288 -i /home/linjiefu/data/sourceVideo/MOBILE_352x288_30_orig_01.yuv -vf 'hwupload=extra_hw_frames=64,format=qsv,vpp_qsv=transpose=clock_hflip' -vframes 10 -f rawvideo -pix_fmt yuv420p -y ./transpose.yuv

**Comment by NaveenKumar-Intel** [comment]
HI @fulinjie

I tried to reproduce the above conversion using sample_vpp with [rotate+mirror+w/h change] using sample_vpp on Clear Linux. However, it seems to work for us.

Following is the log of [rotate+mirror+w/h change] successful conversion using sample_vpp:

`ias@clr-62bd7994d3da4681a0ed9387267cfaff/mnt/padma/test_content/YUV $ **/usr/share/mfx/samples/sample_vpp -sw 352 -sh 288 -scc i420 -dw 288 -dh 352 -dcc i420 -                                                                               iopattern d3d_to_sys -i H264_352w_288h.yuv -o /mnt/padma/tmp/msdk_288w_352h.yuv -mirror 1 -rotate 90 -n 1800**
[WARNING] D3D11 does not support YV12 and I420 surfaces. Input will be converted to NV12 by file reader.
libva info: VA-API version 1.5.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_5
libva info: va_openDriver() returns 0
Input format    NV12
Resolution      352x288
Crop X,Y,W,H    0,0,352,288
Frame rate      30.00
PicStruct       progressive
Output format   NV12
Resolution      288x352
Crop X,Y,W,H    0,0,288,352
Frame rate      30.00
PicStruct       progressive

Video Enhancement Algorithms
Deinterlace     OFF
Signal info     OFF
Scaling         OFF
CromaSiting             OFF
Denoise         OFF
MCTF            OFF
ProcAmp         OFF
DetailEnh       OFF
GamutMapping    OFF
ColorSaturation OFF
ContrastEnh     OFF
SkinToneEnh     OFF
MVC mode        OFF
ImgStab         OFF

IOpattern type                  d3d_to_sys
Number of asynchronious tasks   1
Time stamps checking            OFF
ROI checking                    OFF

MediaSDK impl   hw
HW accelaration is enabled
**MediaSDK ver    1.30**
VPP started
Frame number: 1800
VPP finished

Total frames 1800
Total time 6.93 sec
Frames per second 259.788 fps
ias@clr-62bd7994d3da4681a0ed9387267cfaff/mnt/padma/test_content/YUV $`


Verified the above converted .yuv stream using following GStreamer playback command line and observed that the playback is just fine:

**`gst-launch-1.0 -v filesrc location=/mnt/padma/tmp/msdk_288w_352h.yuv ! rawvideoparse fo                                                                                rmat=i420 width=288 height=352 ! msdkvpp ! glimagesink`**

We also verified [rotate+mirror+w/h change] using sample_vpp for different resolutions such as 1280x720, 640x480 and observed that the conversion & playback is working fine.

**Observed that our MediaSDK ver is 1.30 instead of your MediaSDK ver as 1.29.**
Can you try to reproduce the above issue with latest MediaSDK version.

**Comment by NaveenKumar-Intel** [comment]
HI @fulinjie

I can reproduce the reported issue on CL with resolution 352x288. However, observed that garbage is not seen with following resolutions:
1920x1080, 1280x720, 640x360, 320x240.

I will try to debug it further.

**Comment by fulinjie** [comment]
Hi @NaveenKumar-Intel, is there any update?

**Comment by NaveenKumar-Intel** [comment]
HI @fulinjie,
I couldn't spent time on this issue. I will try to look into it.

**Comment by FurongZhang** [comment]
I have assigned this issue to Jason.

**Comment by MicroYY** [comment]
I will try to debug it.

**Comment by FurongZhang** [comment]
Using the latest open source driver (commit 95e3186) and media SDK, no garbage is seen. Suppose it is fixed by some patches.

**Comment by FurongZhang** [comment]
Please feel free to reopen it if any concern.

**Comment by FurongZhang** [comment]
@fulinjie , need you attention. Using the latest open source driver (commit 95e3186) and media SDK, no garbage is seen.
