### ISSUE TITLE
MFX_ERR_INVALID_VIDEO_PARAM(-15)

### ISSUE THREAD

**Issue by thx4ever** [Intel-Media-SDK/MediaSDK#1590]
I'm trying to encode HEVC with sample_multi_transcode with this par file 

set -o::h265 e5400a06c74d41f5b12d430bbaa23d0b 
-lad 100 -i::h264 input.264 -join -la_ext -hw -async 1 -n 300 -o::sink
-h 1080 -w 1920 -o::h265 output.hevc -b 3000 -join -async 1 -hw -i::source -l 1 -u 4 -n 300

sample_multi_transcode -par 1.par
Multi Transcoding Sample Version 8.4.27.0

Par file is: 1.par

Session 0:
plugin_loader.h :186 [INFO] Plugin was loaded from GUID: { 0x58, 0x8f, 0x11, 0x85, 0xd4, 0x7b, 0x42, 0x96, 0x8d, 0xea, 0x37, 0x7b, 0xb5, 0xd0, 0xdc, 0xb4 } (Intel (R) Media SDK plugin for LA ENC)
MFX HARDWARE Session 0 API ver 1.29 parameters:
Input  video: AVC
Output video: To child session
MFX dll: C:\WINDOWS\SYSTEM32\libmfxhw64.dll

Session 1:
plugin_loader.h :186 [INFO] Plugin was loaded from GUID: { 0xe5, 0x40, 0x0a, 0x06, 0xc7, 0x4d, 0x41, 0xf5, 0xb1, 0x2d, 0x43, 0x0b, 0xba, 0xa2, 0x3d, 0x0b } (Intel (R) Media SDK GPU-Accelerated plugin for HEVC ENCODE)
MFX HARDWARE Session 1 API ver 1.29 parameters:
Input  video: From parent session
Output video: HEVC
MFX dll: C:\WINDOWS\SYSTEM32\libmfxhw64.dll

Pipeline surfaces number (DecPool): 117
Session 0 was joined with other sessions
Session 1 was joined with other sessions

Transcoding started

[ERROR], sts=MFX_ERR_INVALID_VIDEO_PARAM(-15), TranscodingSample::CTranscodingPipeline::Encode, <EncodeOneFrame|Surface2BS> failed at C:\Users\thx4ever\source\repos\MediaSDK\samples\sample_multi_transcode\src\pipeline_transcode.cpp:1451

[ERROR], sts=MFX_ERR_INVALID_VIDEO_PARAM(-15), TranscodingSample::CTranscodingPipeline::Run, CTranscodingPipeline::Run::Encode() [000001905B5B9490]. failed at C:\Users\thx4ever\source\repos\MediaSDK\samples\sample_multi_transcode\src\pipeline_transcode.cpp:4591

 session 1 [000001905B5B9490] failed with status MFX_ERR_INVALID_VIDEO_PARAM shutting down the application...

session [000001905BA056A0] m_bForceStop is set
session [000001905B5B9490] m_bForceStop is set
WARNING: m_bForceStop is set, returning NULL ptr from GetFreeSurface

Transcoding finished

Common transcoding time is 0.342123 sec
-------------------------------------------------------------------------------
*** session 0 [000001905BA056A0] PASSED (MFX_ERR_NONE) 0.341098 sec, 8 frames, 23.454 fps
set -o::h265 e5400a06c74d41f5b12d430bbaa23d0b

*** session 1 [000001905B5B9490] FAILED (MFX_ERR_INVALID_VIDEO_PARAM) 0.306223 sec, 1 frames, 3.266 fps
-lad 100 -i::h264 input.264 -join -la_ext -hw -async 1 -n 300 -o::sink

-------------------------------------------------------------------------------

The test FAILED

[ERROR], sts=MFX_ERR_INVALID_VIDEO_PARAM(-15), wmain, transcode.ProcessResult failed at C:\Users\thx4ever\source\repos\MediaSDK\samples\sample_multi_transcode\src\sample_multi_transcode.cpp:984
plugin_loader.h :212 [INFO] MFXBaseUSER_UnLoad(session=0x000001905B5B9490), sts=0
plugin_loader.h :212 [INFO] MFXBaseUSER_UnLoad(session=0x000001905BA056A0), sts=0

**Comment by NaveenKumar-Intel** [comment]
Hi @thx4ever,

I tried to reproduce the above HEVC Encode issue using sample_multi_transcode on **Clear Linux**. However It seems to work for us.

Observed that supported **HEVC Encode GUID is 6fadc791a0c2eb479ab6dcd5ea9da347** on our Clear Linux. Hence replaced above GUID with this (6fadc791a0c2eb479ab6dcd5ea9da347) in our par file.

**1.par file** looks like this:

set -o::h265 6fadc791a0c2eb479ab6dcd5ea9da347
-lad 100 -i::h264 1080p_30fps.h264 -join -la_ext -hw -async 1 -n 300 -o::sink
-h 1080 -w 1920 -o::h265 output.hevc -b 3000 -join -async 1 -hw -i::source -l 1 -u 4 -n 300

Following is the log of **successful transcode**:

ias@clr-9bd0fc4344f241bf8604d5c492b70a03/tmp $ /usr/share/mfx/samples/sample_multi_transcode -par 1.par
Multi Transcoding Sample Version 8.4.27.

Par file is: 1.par

libva info: Open new log file /tmp/libva_params.064846.thd-0x00000957 for the thread 0x00000957
libva info: LIBVA_TRACE is on, save log into /tmp/libva_params.064846.thd-0x00000957
libva info: VA-API version 1.5.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_5
libva info: va_openDriver() returns 0
Session 0:
plugin_loader.h :186 [INFO] Plugin was loaded from GUID: { 0x58, 0x8f, 0x11, 0x85, 0xd4, 0x7b, 0x42, 0x96, 0x8d, 0xea, 0x37, 0x7b, 0xb5, 0xd0, 0xdc, 0xb4 } (Intel (R) Media SDK plugin for LA ENC)
**MFX HARDWARE Session 0 API ver 1.30 parameters:**
Input  video: AVC
Output video: To child session

Session 1:
plugin_loader.h :186 [INFO] Plugin was loaded from GUID: { 0x6f, 0xad, 0xc7, 0x91, 0xa0, 0xc2, 0xeb, 0x47, 0x9a, 0xb6, 0xdc, 0xd5, 0xea, 0x9d, 0xa3, 0x47 } (Intel (R) Media SDK HW plugin for HEVC ENCODE)
[WARNING] Configuration changed on the Query() call
mfx.LowPower:0 changed to mfx.LowPower:32
mfx.BRCParamMultiplier:0 changed to mfx.BRCParamMultiplier:1
ext.265P.PicHeightInLumaSamples:1080 changed to ext.265P.PicHeightInLumaSamples:1088
**MFX HARDWARE Session 1 API ver 1.30 parameters:**
Input  video: From parent session
Output video: HEVC

Pipeline surfaces number (DecPool): 117
libva info: Save context 0x10000000 into log file /tmp/libva_params.064846.thd-0x00000957
Session 0 was joined with other sessions
libva info: Save context 0x20000000 into log file /tmp/libva_params.064846.thd-0x00000957
libva info: LIBVA_TRACE_CODEDBUF is on, save codedbuf into /tmp/libva_enc_data.064846.ctx-0x20000000
Session 1 was joined with other sessions

Transcoding started
libva info: Open new log file /tmp/libva_params.064846.thd-0x00000969 for the thread 0x00000969
libva info: Open new log file /tmp/libva_params.064846.thd-0x0000095c for the thread 0x0000095c
libva info: Open new log file /tmp/libva_params.064846.thd-0x0000095d for the thread 0x0000095d
libva info: Open new log file /tmp/libva_params.064900.thd-0x0000096a for the thread 0x0000096a
...
Transcoding finished

Common transcoding time is 14.5991 sec
-------------------------------------------------------------------------------
*** session 0 [0x55f3e3a748e0] **PASSED** (MFX_ERR_NONE) 14.5544 sec, 300 frames
set -o::h265 6fadc791a0c2eb479ab6dcd5ea9da347

*** session 1 [0x55f3e3aaf650] **PASSED** (MFX_ERR_NONE) 14.5988 sec, 300 frames
-lad 100 -i::h264 1080p_30fps.h264 -join -la_ext -hw -async 1 -n 300 -o::sink

-------------------------------------------------------------------------------

The test PASSED
plugin_loader.h :212 [INFO] MFXBaseUSER_UnLoad(session=0x0x55f3e3aaf650), sts=0
plugin_loader.h :212 [INFO] MFXBaseUSER_UnLoad(session=0x0x55f3e3a748e0), sts=0
ias@clr-9bd0fc4344f241bf8604d5c492b70a03/tmp $


Observed that our MFX HARDWARE API ver is 1.30 instead of your MFX HARDWARE API ver as 1.29.

Can you try to reproduce the above issue with latest MFX HARDWARE API ver.

Thanks,
NaveenKumar
