### ISSUE TITLE
sample_encode, fread overhead

### ISSUE THREAD

**Issue by DavidMarec** [Intel-Media-SDK/MediaSDK#163]
Running tests with the help of `sample_encode`. I' m facing performance issues.

I found that  `sample_encode` stay stuck through the vfs subsystem many times by calling `fread` .
The issue maybe located in the function below

https://github.com/Intel-Media-DK/MediaSDK/blob/master/samples/sample_common/src/sample_utils.cpp#L143

There is a full bunch of `fread` calls within loop statements in this `LoadNextFrame` function. 
Moreover, some loops encloses a single call to  `fread` with additionally an error check.

* Why do not replace some loops by requesting `fread`  to download a  __single__  bigger data block instead of __many__ smaller one ?
* What about rather using c++ ifstream (a bit more optimized, maybe) ?

**Comment by eero-t** [comment]
> Running tests with the help of sample_encode. I' m facing performance issues. I found that sample_encode stay stuck through the vfs subsystem many times by calling fread .

Found with which tool?  Stuck how?  In which use-case?  From what storage media you're reading the data?

> The issue maybe located in the function below

* MediaSDK reads are at minimum for whole the width, not few bytes at the time
* C-library already buffers reads (I think 4K blocks)
* kernel does also some read-ahead for the data on disk

-> If your use-case is really blocking on disk reads, I think your problem is elsewhere than in MediaSDK disk reads.

For example:
* You're running out of memory so your kernel does a lot of paging / swapping (Media playback needs quite a bit of memory itself)
* You have really slow media or maybe there are disk errors?
