### ISSUE TITLE
Presentation timestamps API usage for decoder 

### ISSUE THREAD

**Issue by HermanMolinder** [Intel-Media-SDK/MediaSDK#1658]
I got a similar issue as explained here:
https://software.intel.com/en-us/forums/intel-media-sdk/topic/607006

The problem is that the input PTS-s aren't monotonically increasing and I need to know when the MSDK has "consumed" the timestamp from my mfxBitsream, so I can feed it with the next timestamp. The goal is of course to have monitonically increasing timestamps on the decoder output, after frame reordering.

The MFX_BITSTREAM_COMPLETE_FRAME flag it's not a solution for me. The input container format is a Transport Stream with PES packets. According to MPEG standard a PES packet can contain multiple access units (multiple frames) and also single fields (half a frame). Therefore I can't guarantee that each DecodeFrameAsync call contains exactly one frame.

**Comment by dmitryermilov** [comment]
@dmitry-gurulev , can you please help?

**Comment by dmitry-gurulev** [comment]
@HermanMolinder, what demuxer do u use? Usually demuxers produce frame-by-frame (field) output. And maybe u could use [samples/sample_common/src/avc_spl.cpp](https://github.com/Intel-Media-SDK/MediaSDK/blob/master/samples/sample_common/src/avc_spl.cpp) to get complete frames.

**Comment by HermanMolinder** [comment]
@dmitry-gurulev We use our own demuxer, which parses TS and PES headers. From the streams I've tested I've gotten it to work for H264 and HEVC, but I still have issues with some MPEG2 streams.

I need to read up on the MPEG standard, but I think I recall that multiple frames per PES is only allowed H264 and HEVC. In that case I could use MFX_BITSTREAM_COMPLETE_FRAME for MPEG2 streams only.

However this is more of a general concern on how the MSDK is supposed to be used when dealing with PTS values in TS container format. For me it has been a lot of reverse engineering regarding timestamps, because the API doesn't provide any feedback when a frame unit is internally created and a timestamp is provided for it.

**Comment by dmitryermilov** [comment]
Hi @HermanMolinder , 

I got your concern and as a person who worked on MSDK integration into different frameworks I agree that it's a gap. I mean the fact that COMPLETE_FRAME is required for timestamp processing.  There are future plans to improve it but unfortunately _right now_ there is no other API for PTS handling.

Could you share details about the MPEG2 issues?  If it's sensitive info, please feel free to ping me via email. I can suggest support by explaining MSDK internal decoders logic if will will help your .

**Comment by HermanMolinder** [comment]
Hi @dmitryermilov ,

Thank you for the reply. It's good for me to know that you're aware of this. Then I don't need to be concerned that I'm using the API in the wrong way.

My implementation of the PTS handling has grown a bit complex, but I can try to give a simplified explanation here:

* Feed DECODE_FRAME with one PES payload worth of data together with the PTS value of that PES.
* Feed the next PES/PTS if one of the following conditions are true:
    1) DECODE_FRAME has consumed the complete PES input bitstream (except a few bytes for 
        possible start code)
    2) MORE_DATA is returned
* If none of the above conditions are true I feed it with the same PES/PTS

The above logic seems to work with the H264 and HEVC streams I've tested, and some MPEG2 streams. However I still have problem with some other MPEG2 streams. For those streams it occasionally misses a timestamp. See attached file of output PTS values:
[MPEG2_output_pts.txt](https://github.com/Intel-Media-SDK/MediaSDK/files/3674789/MPEG2_output_pts.txt)

I still haven't tried COMPLETE_FRAME, but this may be a solution for me. I've also looked at the MSDK source code, but it's hard to understand. An explanation of the internal logic would be helpful.

**Comment by HermanMolinder** [comment]
I found the document I recalled. It was for DVB compliant decoders.

Chapter 4.1.6.9:
https://www.etsi.org/deliver/etsi_ts/101100_101199/101154/02.06.01_60/ts_101154v020601p.pdf

It states for MPEG2:
The IRD may be able to accept and decode bitstreams which contain multiple video pictures in a
single PES.

For H264:
The IRD shall support decoding and displaying bitstreams, which contain multiple complete
access units in a single PES packet. It is strongly recommended that the IRD also supports
decoding and displaying bitstreams that contain fractions of access units in PES packet. 

For HEVC:
The HEVC IRD shall support decoding and displaying bitstreams where each PES packet contains
exactly one complete AU.

**Comment by HermanMolinder** [comment]
Hi again,

I've got it to work with MPEG2 now, without the use of COMPLETE_FRAME flag. It was a bug in my implementation.

It's hard to say that my implementation will work for all types of streams, but at least it seems to work for those I've tested. For now I'm satisfied! If I run in to problems in the future I will keep you notified.

@dmitryermilov You don't need to spend time explaining the internal logic, as it works for me now. If you don't want to, of course. I'm still glad I could provide you this feedback and that you seem to be aware of it.

Thanks!

**Comment by dmitryermilov** [comment]
Hi Herman,

Sorry for delayed reply. It's great it already got it working!
Anyway, regarding the logic, let's me share some key points. I hope it will help. 
- NALU parsing. msdk decoders **in general** don't require app to pass complete frame (or field), or the whole slice in one DecodeFrameAsync call. In order to achieve it there are internal NALU parsers. So that decoder can find some NALU in bistream, the bistream passed to decoder should have beginning (I mean start code) of current NALU and start code of next NALU. In case of COMPLETE_FRAME flag, decoders don't search for start code of next frame (the first slice of next frame).
- an internal frame is being created when two conditions are met:
  - there is a free surface from application. If no - decoder returns MFX_ERR_MORE_SURFACES
  - when parser finds the first slice of frame.
- an internal frame becomes completed when :
  - decoder finds next SPS/PPS
  - decoder finds the first slice of next frame
  - COMPLETE_FRAME flag is set.
- When decoders assign PTS's (from app) to internal frames? You know, I was sure **all** decoders make this assignment using PTS of the first slice:  [AVC code](https://github.com/Intel-Media-SDK/MediaSDK/blob/fe8538c74fc1d4d0049832c1314974c30d9d1cd0/_studio/shared/umc/codec/h264_dec/src/umc_h264_task_supplier.cpp#L3898), [HEVC code](https://github.com/Intel-Media-SDK/MediaSDK/blob/fe8538c74fc1d4d0049832c1314974c30d9d1cd0/_studio/shared/umc/codec/h265_dec/src/umc_h265_task_supplier.cpp#L2349). But no - I just found that in MPEG2 we re-write frame timestamp on **each** slice: https://github.com/Intel-Media-SDK/MediaSDK/blob/fe8538c74fc1d4d0049832c1314974c30d9d1cd0/_studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_decoder.cpp#L504 . I need to align this logic with AVC/HEVC. I'll prepare a patch soon.

**Comment by HermanMolinder** [comment]
Hi Dmitry,

Thank you. This was really helpful information.
The different behavior you found for MPEG2 can explain what I have seen and been struggling with.

**Comment by dmitryermilov** [comment]
You're always welcome. 
Please try https://github.com/Intel-Media-SDK/MediaSDK/pull/1700/ . Meanwhile I'll trigger internal regression testing.

**Comment by dmitryermilov** [comment]
There are no regressions in internal validation. @HermanMolinder , please let me know if this change helps you.

**Comment by HermanMolinder** [comment]
@dmitryermilov 
Thank you!
I will notify you when I've tried this. Right now I need to focus on other things, so I prepare you that it might take a while til I have time to test it.

**Comment by dmitryermilov** [comment]
Hi Herman,

You're welcome! Sure. No rush. 

Regards,
Dmitry

**Comment by HermanMolinder** [comment]
Hi @dmitryermilov,

We've updated to Media SDK 20.1.0 and I just want to inform you that the changes in #1700 works as expected.

BR
Herman

**Comment by dmitryermilov** [comment]
Hi Herman,

Thanks for confirmation!

Regards,
Dmitry
