### ISSUE TITLE
"IGD Aperture Size" influence

### ISSUE THREAD

**Issue by alektg** [Intel-Media-SDK/MediaSDK#1724]
Hi,
Text below doesn't describe an issue/problem/bug/error, it is a theoretical question only.

Does the BOIS setting "IGD Aperture Size" affect video decoding/encoding performance?
In other words,

Can "IGD Aperture Size" changes lead to increased/decreased frames-per-second score (of IMSDK-HW encoders/decoders)? 

Can too small (or too big) "IGD Aperture Size" value cause a MFX_ERR_GPU_HANG occurrences during coders work?

Environment: win10 host, without any virtual machines. One or several (simultaneous) decoding/encoding applications.

**Comment by dmitryermilov** [comment]
Hi @alektg ,

Linux: Aperture size doesn't define a max size of available video memory but it defines size of so called Graphics Translation Table. It's _might be_ used in **conversion "video to system" memory.** On Gen9 systems media driver does indirectly use GTT because vaMapBuffer internally uses mmap_gtt for memory mapping. Regarding oversubscription:  if the active mappings oversubscribe the available aperture space, you would get a slowdown since i915 will have to unmap and map objects as userspace is accessing the mapped memory (via the page fault mechanism). (So already slow access via mmap_gtt would be even slower.) On Gen11 mmap_gtt  isn't used by driver (cpu based "video to system" is used).

Windows: AFAIK, aperture is not used there. Unlike the gtt map of linux (pre-gen11), on Windows lock surface is actually GPU-copied between video and system memory. So aperture is not used and the size should not impact performance.

Regards,
Dmitry

**Comment by alektg** [comment]
Hi @dmitryermilov ,
You gave thorough and exhaustive answer.
Thanks!

**Comment by dmitryermilov** [comment]
You're welcome.
