### ISSUE TITLE
3:2 Pull Down MFXVideoDECODE

### ISSUE THREAD

**Issue by Nastooh-Inca** [Intel-Media-SDK/MediaSDK#1801]
Hi 
Got an interlaced clip that midway does a pull down, i.e., tb,tb,tb, ... tbt,btb,...,tb, tb ....
I am wondering if MFXVideoDECODE is able to deal with this, and if so, how would I be able to detect such transitions.
Cheers,

**Comment by dmitryermilov** [comment]
Hi @Nastooh-Inca ,

Are you talking about Table D-1? If so, you can get this info from https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/mediasdk-man.md#picstruct 

MFX_PICSTRUCT_FIELD_REPEATED is dedicated to tbt, btb cases. Please note that in order to get MFX_PICSTRUCT_FIELD_REPEATED you need to initialize decoder with [ExtendedPicStruct](https://github.com/Intel-Media-SDK/MediaSDK/blob/89b7dcf675b7a5a7c10e69c8ed3c943aa78bcbdc/api/include/mfxstructures.h#L326).

Please also see decoder implementation, just for your reference :
https://github.com/Intel-Media-SDK/MediaSDK/blob/master/_studio/mfx_lib/decode/h264/src/mfx_h264_dec_decode.cpp#L1535 

So, in order to detect the transition you need to check presence/absence of MFX_PICSTRUCT_FIELD_REPEATED in output surface PicStruct field.

**Comment by Nastooh-Inca** [comment]
Thank you for the feedback. Do theses enums hold for all formats, i.e. MPEG2, AVC and HEVC, or as noted in the table, just for AVC?

**Comment by dmitryermilov** [comment]
Hi @Nastooh-Inca , 

Do you have other questions/concerns ?
