### ISSUE TITLE
MFXVideoENCODE_Reset Results in Key Frame

### ISSUE THREAD

**Issue by vassjozsef** [Intel-Media-SDK/MediaSDK#1862]
We integrated Intel QuickSync GPU video encoding into Discord. WebRTC bandwidth adaptation updates bitrate quite often (sometimes every second). We use  `MFXVideoENCODE_Reset` to update bitrate. The next frame is encoded as an I frame, which is highly undesirable.

I have prepared https://github.com/vassjozsef/MediaSDK that shows the issue. I increment bitrate by 10% after every 100th frame and print out encoded frame type.

Please see https://github.com/vassjozsef/MediaSDK/blob/master/README-Discord.md for more information.

Do you know why is this happening? Is there any workarounds?

**Comment by dmitryermilov** [comment]
Hi @vassjozsef ,

I'll split the answer in 3 parts:

- I assume (without knowing init params) IDR is inserted because of this
 https://github.com/Intel-Media-SDK/MediaSDK/blob/master/_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp#L1320-L1329
Could you try disabling HRD by mfxExtCodingOption::VuiNalHrdParameters/mfxExtCodingOption::VuiVclHrdParameters and check again?
- Can you please share more about BRC mode (CBR, VBR, LookAhead, SW BRC) you'd like to use and other requirements like GOP params, latency (low delay?), etc? 
- Right now we're developing new features and tools for game steaming scenarios. Do you have an Intel account (application engineering or technical consulting engineer) assigned to support you? We could share details via such contact.

**Comment by vassjozsef** [comment]
Hello @vassjozsef,

Your suggestion worked perfectly (I updated my sample code), disabling HDR fixed the issue! I am using parameters from https://github.com/open-webrtc-toolkit/owt-client-native/blob/master/talk/owt/sdk/base/win/msdkvideoencoder.cc#L165-#L196 and just added https://github.com/open-webrtc-toolkit/owt-client-native/blob/master/talk/owt/sdk/base/win/msdkvideoencoder.cc#L198-#L204 as you suggested.

I would be interested in starting conversation about low latency game streaming.

**Comment by dmitryermilov** [comment]
Hi @vassjozsef ,

> Your suggestion worked perfectly (I updated my sample code), disabling HDR fixed the issue! 

Great!

> I would be interested in starting conversation about low latency game streaming.

Could you send me an email (dmitry.ermilov@intel.com ) to start conversation?
