### ISSUE TITLE
Install the mfx headers in $PREFIX/include/mfx instead of $PREFIX/include

### ISSUE THREAD

**Issue by xhaihao** [Intel-Media-SDK/MediaSDK#199]
Hi,

The open-source MediaSDK installs the mfx headers in $PREFIX/include however the open-source  dispatcher (https://github.com/lu-zero/mfx_dispatch) for Intel MediaSDK installs the mfx headers in $PREFIX/include/mfx, the open-source dispatcher is used widely where pkg-config is supported nowadays.  Could you change the install path to $PREFIX/include/mfx for the open source MediaSDK ? If so, the open-source dispatcher is unnecessary when using the open-source MediaSDK. 

Thanks
Haihao

**Comment by onabiull** [comment]
Hello,
  Code in https://github.com/lu-zero/mfx_dispatch is just a fork of Dispatcher, and I was not even aware about it :). Current version of MediaSDK dispatcher in open source MediaSDK also provides pkg-config files. You may even change default headers location by altering CMAKE_INSTALL_INCLUDEDIR. Still it not clear to me how adding "mfx" would help end users.

**Comment by sreerenjb** [comment]
It is always good to have a separate "mfx" directory for mediasdk install headers rather than putting everything in PREFIX/include.
This is the same pattern we use for most of the libraries, for eg: all libva headers are in PREFIX/va .

**Comment by lizhong1008** [comment]
Agree to move headers to PREFIX/mfx/include because MSDK is not a system libary.  It will be more convenient to mange these header if with a separate "mfx" folder.
And https://github.com/lu-zero/mfx_dispatch has been widely used when build applications(ffmpeg/gstreamer/handbrake...) with MediaSeverStuido. Would better the open source MSDK can assign with it. Else we need to an addtional step(copy header to Prefix/mfx/include) , or update these applications to use header located in Prefix/inlcude.

**Comment by onabiull** [comment]
We are ok with suggested change. Could you please provide a PR? We'll review and merge it.
