### ISSUE TITLE
Is there any tools to monitor qsv's memory usage like nvidia-smi for NVIDIA?

### ISSUE THREAD

**Issue by YaboWei** [Intel-Media-SDK/MediaSDK#2079]

**Comment by AntonGrishin** [comment]
We have a [metrics monitor tool](https://github.com/Intel-Media-SDK/MediaSDK/tree/master/samples/metrics_monitor) which is part of our samples ([documentation](https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/samples/readme-metrics_monitor_linux.md))

**Comment by YaboWei** [comment]
> We have a [metrics monitor tool](https://github.com/Intel-Media-SDK/MediaSDK/tree/master/samples/metrics_monitor) which is part of our samples ([documentation](https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/samples/readme-metrics_monitor_linux.md))

But metrics_monitor has no memory usage message:
`[root@bjm7-tc96 _bin]# LD_LIBRARY_PATH=./ ./metrics_monitor
RENDER usage: 48.17,	VIDEO usage: 43.18,	VIDEO_E usage: 0.00	VIDEO2 usage: 9.97	GT Freq: 1099.87
RENDER usage: 56.62,	VIDEO usage: 42.62,	VIDEO_E usage: 0.00	VIDEO2 usage: 12.78	GT Freq: 1099.88
RENDER usage: 49.56,	VIDEO usage: 42.88,	VIDEO_E usage: 0.00	VIDEO2 usage: 10.69	GT Freq: 1099.88
RENDER usage: 36.75,	VIDEO usage: 16.91,	VIDEO_E usage: 0.00	VIDEO2 usage: 6.95	GT Freq: 1099.88
RENDER usage: 57.66,	VIDEO usage: 51.24,	VIDEO_E usage: 0.00	VIDEO2 usage: 16.29	GT Freq: 1099.88
RENDER usage: 61.22,	VIDEO usage: 40.27,	VIDEO_E usage: 0.00	VIDEO2 usage: 10.98	GT Freq: 1099.88
RENDER usage: 53.40,	VIDEO usage: 40.59,	VIDEO_E usage: 0.00	VIDEO2 usage: 14.27	GT Freq: 1099.86
RENDER usage: 46.76,	VIDEO usage: 31.50,	VIDEO_E usage: 0.00	VIDEO2 usage: 9.76	GT Freq: 1099.88`

**Comment by dmitryermilov** [comment]
Hi @YaboWei ,

I'm not aware of such tool right now. But it doesn't seem to be strongly needed right now because in integrated graphics, video memory is the same RAM memory.
For system memory, you can use _top_ tool to check the VIRT (total memory allocation) and RES (memory working set) size. Please note that the memory working set also includes some mapped buffers from video memory.
Regarding video memory, you can run “cat /sys/kernel/debug/dri/0/i915_gem_objects”

**Comment by eero-t** [comment]
> I'm not aware of such tool right now. But it doesn't seem to be strongly needed right now because in integrated graphics, video memory is the same RAM memory.
> For system memory, you can use _top_ tool to check the VIRT (total memory allocation) and RES (memory working set) size.

*Single* video pipeline can take gigabytes of system memory for GPU usage, with larger resolutions, depending on selected rate control.

Typically only way you see that memory usage is by running out of swap (because that memory is non-swappable), like in this X server bug:
https://bugs.freedesktop.org/show_bug.cgi?id=106106

Also, there's no way to control / limit that. That's not Intel specific issue though, but a generic one for the whole kernel DRM subsystem.  There's 7 years old CVE about it, see: https://bugzilla.kernel.org/show_bug.cgi?id=60533

> Please note that the memory working set also includes some mapped buffers from video memory.
> Regarding video memory, you can run “cat /sys/kernel/debug/dri/0/i915_gem_objects”

This is currently the only way currently to monitor DRM memory usage with Intel GPUs.  Happily it tells also which processes / contexts are using the memory, not just how much is consumed.

I future, GPU memory usage can hopefully be monitored *and* controlled with cgroup (there have been different kernel patch series for that from Intel & AMD during the years, but they haven't yet converged to a shared DRM one that would be acceptable by kernel cgroup maintainers).
