### ISSUE TITLE
MFXVideoDECODE_DecodeHeader() returns wrong frame rate

### ISSUE THREAD

**Issue by snw1** [Intel-Media-SDK/MediaSDK#2202]
Hello
I'm developing a video processing software using Intel MediaSDK and ffmpeg libraries
Few days ago out client faced a problem with video stream transcoding
After investigation it was transpired that MediaSDK returns wrong frame rate after header decoding:
```
Frame rate: 6000/2
```
Meanwhile, ffmpeg returns correct frame rate (30 fps):
```
    Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn, 6k tbc
```
MPEG-TS stream dump and C++ reproduction example are included
VLC is playing that dump correctly
C++ reproduction example:
```c++
#include <iostream>
#include <fstream>
#include <vector>
#include <mfxstructures.h>
#include <mfxsession.h>
#include <mfxvideo.h>

constexpr auto INPUT = "T6014.h264";
constexpr size_t PROBE_SIZE = 1024 * 1024;

int main()
{
  std::vector<mfxU8> data(PROBE_SIZE);
  mfxSession session{};
  mfxVideoParam params{};
  mfxBitstream bitstream{};
  bitstream.Data = data.data();
  bitstream.MaxLength = data.size();
  std::ifstream is;
  try {
    mfxVersion version{{3, 1}};
    if (mfxStatus status = MFXInit(MFX_IMPL_HARDWARE_ANY, &version, &session); status != MFX_ERR_NONE)
      throw std::runtime_error("MFXInit failed, status: " + std::to_string(status));
    is.open(INPUT);
    if (!is.is_open())
      throw std::runtime_error(std::string("Failed to open ") + INPUT);
    is.read(reinterpret_cast<char*>(data.data()), data.size());
    if (!is.good())
      throw std::runtime_error(std::string("Failed to read ") + std::to_string(data.size()) + " bytes from " + INPUT);
    bitstream.DataLength = data.size();
    params.mfx.CodecId = MFX_CODEC_AVC;
    if (mfxStatus status = MFXVideoDECODE_DecodeHeader(session, &bitstream, &params); status != MFX_ERR_NONE)
      throw std::runtime_error("MFXVideoDECODE_DecodeHeader failed, status: " + std::to_string(status));
    std::cout << "Frame rate: " << params.mfx.FrameInfo.FrameRateExtN << "/" << params.mfx.FrameInfo.FrameRateExtD << std::endl;
  } catch (const std::exception& ex) {
    std::cerr << "ERROR: " << ex.what() << std::endl;
  }
  is.close();
  MFXClose(session);
  return 0;
}
```
Dump: https://www.dropbox.com/s/dqsre6aetrvw2ab/T6014.ts?dl=0

**Comment by wangyan-intel** [comment]
@snw1 I cannot get your clips from dropbox. Could you please share it by the other way? Like google driver. Thanks.

**Comment by dmitryermilov** [comment]
Hi @snw1 ,

I looked. Generally there is no bug in MSDK. By AVC spec, frame rate is calculated as : "framerate = vui.time_scale / vui.num_units_in_tick / 2".  "/2" is to get **frame** rate. 
In the given stream time_scale is 6000, num_units_in_tick is 1. Framerate 3000 fps doesn't make sense and contradicts to spec (I can find a confirmation is needed). So generally the stream is invalid. 
On the other hand, in MSDK decoders the strategy is to handle invalid/corrupted streams in a reasonable way when it's possible. E.g. usually if we detect some wrong syntax element in NALU, we skip the whole NALU. But for VUI (which are optional) it is not reasonable because we'll skip the whole SPS (which actually be a single one across the whole stream).
I think **after** headers parsing and during filling mfxVideoParams we can verify if framerate looks valid. If not, we'll set a "default frame" (30fps). @dmitry-gurulev , what do you think ?

**Comment by snw1** [comment]
Hi, Dmitry
> I looked. Generally there is no bug in MSDK. By AVC spec, frame rate is calculated as : "framerate = vui.time_scale / vui.num_units_in_tick / 2". "/2" is to get **frame** rate.
> In the given stream time_scale is 6000, num_units_in_tick is 1. Framerate 3000 fps doesn't make sense and contradicts to spec (I can find a confirmation is needed). So generally the stream is invalid.
Thanks for the assistance
> I think **after** headers parsing and during filling mfxVideoParams we can verify if framerate looks valid. If not, we'll set a "default frame" (30fps).
We've already made the similar fix in our code

**Comment by wangyan-intel** [comment]
This issue has been fixed on application side.
