### ISSUE TITLE
Encode existing ID3D11Texture2D

### ISSUE THREAD

**Issue by paniksystem** [Intel-Media-SDK/MediaSDK#2205]
Hi again,

I am trying to encode an existing ID3D11Texture2D acquired from the OutputDuplication API. But no matter what i do i get a grey encoded video. 

I think my understanding of what needs to be done to work is flawed so I've made a simple reproducer at https://github.com/paniksystem/media-sdk-simple

Thanks

**Comment by dmitryermilov** [comment]
@KseniyaTikhomirova , @SergeySol , can you please take a look at https://github.com/paniksystem/media-sdk-simple/blob/master/entry.cpp ? I'm not a big expert in windows screen capturing.

**Comment by KseniyaTikhomirova** [comment]
@paniksystem, @dmitryermilov,
Hi guys, what is the resolution you try it with? The first gap I see is that you use CopyResource. For some cases - as example, full HD case - aligned surface allocated for Media SDK encoder (1920x1088) is bigger than the one obtained with desktop duplication API  (1920x1080). CopyResource requires strict match of fourCC group, width and height, otherwise operation will not be performed. In this case it is better to replace it with CopySubresourceRegion and do copy with crops.

**Comment by paniksystem** [comment]
Good catch ! That was it.

Thank you

**Comment by hassan379** [comment]
@paniksystem  I would like to know how to encode existed ID3D11Texture2D using qsv
but ur link is not working anymore. can u please reactivate it again?
thx in advance
