### ISSUE TITLE
GPU hang, no way to recover only if reboot host

### ISSUE THREAD

**Issue by YaboWei** [Intel-Media-SDK/MediaSDK#2270]
CentOS Linux release 7.4.1708 (Core)
kernel 4.18
msdk 19.4
E3-1585L v5

![image](https://user-images.githubusercontent.com/26398513/89607992-6e9a5400-d8a6-11ea-87bf-415029275931.png)

Sorry for I can not reproduce this problem.

How can I detect the GPU hang?

**Comment by eero-t** [comment]
> E3-1585L v5

Ok, that's a Skylake: https://ark.intel.com/content/www/us/en/ark/products/93741/intel-xeon-processor-e3-1585l-v5-8m-cache-3-00-ghz.html

> kernel 4.18
> Sorry for I can not reproduce this problem

GPU hangs could be due to issue in kernel, media driver, or what MSDK does on top of media-driver, but this is really old kernel.

As you don't tell what's your use-case / how to reproduce this, *you* would need to find out which component is responsible for the issue, reproduce it with latest version of that one, and then report the issue to the correct issue tracker (kernel issue tracker is at freedesktop.org, not in github like MSDK and media-driver ones are).

> How can I detect the GPU hang?

Typically the running program fails when the corresponding GPU operation fails.  GPU hang is noted in dmesg, and dmesg tells where in sysfs to get the error information that you need to attach to the bug tracker.

With the Level Zero API, there will also be an API for getting RAS information.

**Comment by daleksan** [comment]
@YaboWei Please take a look on the section in release notes: [GPU Hang Reporting and Recovery](https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/mediasdk_release_notes.md#GPU_Hang_Reporting_And_Recovery)

**Comment by eero-t** [comment]
> GPU hang, no way to recover only if reboot host

Hang recovery is kernel responsibility.  If this bug is about recovery, you've filed it to wrong place => close?

**Comment by daleksan** [comment]
@YaboWei feel free to re-open if it still actual
