### ISSUE TITLE
mfx occasionaly creates corrupted I-Frame

### ISSUE THREAD

**Issue by vyacheslavs** [Intel-Media-SDK/MediaSDK#2511]
Hi. I'm using latest media-sdk + latest libva-intel. Kernel 4.19. Using sample_encode tool. Once in 2-3 hours corrupted frame produced.
```
mediasdk_libva_version: 1.10.0
mediasdk_build_info: Linux-5.4.0-54-generic 5.4.0-54-generic | GNU 9.2.0 | glibc 2.31
mediasdk_git_commit: hashsum unknown
mediasdk_copyright: Copyright(c) 2007-2020 Intel Corporation
mediasdk_product_name: Intel(R) Media SDK
mediasdk_version: 20.5.0
mediasdk_api_version: 1.34
```
```
VGA compatible controller: Intel Corporation Device 191b (rev 06) (prog-if 00 [VGA controller])
```
```
#define DRIVER_NAME		"i915"
#define DRIVER_DESC		"Intel Graphics"
#define DRIVER_DATE		"20180719"
#define DRIVER_TIMESTAMP	1532015279
```
```
./sample_encode h264 -i test.yuv -o test.h264 -w 1920 -h 1080 -f 30 -nobref -b 5000 -u medium -cbr -r 1 -x 1 -g 30
libva info: VA-API version 1.10.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
Encoding Sample Version 8.4.27.0

Input file format	YUV420
Output video		AVC 
Source picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Destination picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Frame rate	30.00
Bit rate(Kbps)	5000
Gop size	30
Ref dist	1
Ref number	1
Idr Interval	0
Target usage	balanced
Memory type	system
Media SDK impl		hw
Media SDK version	1.34
```

**Comment by vyacheslavs** [comment]
[bad.zip](https://github.com/Intel-Media-SDK/MediaSDK/files/5618687/bad.zip)

**Comment by vyacheslavs** [comment]
Could you please tell me what's wrong? Can provide more information if needed. Thank you !!!

**Comment by vyacheslavs** [comment]
Looks like it's a kernel issue. I've tried 4.16 and everything is ok. 23 hours without any corrupted frames. Now I'm going to investigate what's wrong with my 4.19.

**Comment by vyacheslavs** [comment]
Hi @dmitryermilov 
Turning on CONFIG_INTEL_IDLE somehow makes the mfx to create corrupted frames on 4.19 (taken from linux-stable: git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git). Can anyone confirm this? Or is it well known issue?

**Comment by dmitryermilov** [comment]
Hi @vyacheslavs ,

Are there any suspicious logs in dmesg output when the issue occurs?
Generally, it's hard to comment. At least I'm not aware of known problems triggered by CONFIG_INTEL_IDLE. MediaSDK doesn't have dependencies from kernel/i915 kernel mode driver.  The user mode media driver has dependencies from KMD but again I have never heard of issues related to CONFIG_INTEL_IDLE. I'd propose to reproduce the issue with https://cgit.freedesktop.org/drm-tip .  i915 kernel maintainers usually ask for such info.  If the issue is seen, please submit a bug at https://bugs.freedesktop.org/ (please see https://bugs.freedesktop.org/show_bug.cgi?id=110247 as an example).
Also I'd propose to duplicate the issue at UMD repo: https://github.com/intel/media-driver/issues 
@dvrogozh , do you have anything to add?

**Comment by vyacheslavs** [comment]
No suspicious logs in dmegs output found.
