### ISSUE TITLE
No explicit license grant or no license agreement corresponding to references in files

### ISSUE THREAD

**Issue by rahulmohang** [Intel-Media-SDK/MediaSDK#2937]
Hello, 

The header of the following file has the statement: 

"No part of the Material may be used,
// copied, reproduced, modified, published, uploaded, posted, transmitted,
// distributed or disclosed in any way without Intel's prior express written
// permission. No license under any patent, copyright or other intellectual
// property rights in the Material is granted to or conferred upon you,
// either expressly, by implication, inducement, estoppel or otherwise.
// Any license under such intellectual property rights must be express and
// approved by Intel in writing."

https://github.com/Intel-Media-SDK/MediaSDK/blob/master/contrib/ipp/src/ippversion.h. 

The following files have references to license agreements from Intel, but the corresponding license agreement has not been found:
https://github.com/Intel-Media-SDK/MediaSDK/blob/master/tools/tracer/dumps/dump_mfxfei.cpp
https://github.com/Intel-Media-SDK/MediaSDK/blob/master/tools/tracer/gui/Properties/AssemblyInfo.cs
https://github.com/Intel-Media-SDK/MediaSDK/blob/master/tools/tracer/gui/*.cs

Can you please let me know the license that applies to the files mentioned above?

**Comment by rahulmohang** [comment]
Thank you @tjyrinki.

**Comment by dvrogozh** [comment]
These proprietary headers on some files, including tracer, got missed to be cleaned up on initial open source attempt of respective files. The license was supposed to be MIT. However, historically some sources (like samples) were rereleased under BSD-3 while library got released (later on) under MIT. Unfortunately that got little mixed up, I see some files under BSD-3 outside of samples. We are clarifying this right now.

As for the proprietary headers - see #2939 with the fix.

> I'm not sure if MediaSDK is seeing maintenance any more.

It is still maintained for the features/platforms it supports. New platforms/new features are added to https://github.com/oneapi-src/oneVPL-intel-gpu

> I'm not finding a trace of the tracer (...) on the oneAPI side.

Because https://github.com/oneapi-src/oneVPL-intel-gpu contains only runtime library for the oneVPL while MSDK contains everything (dispatcher library, runtime, samples, tools, tracer).
