### ISSUE TITLE
MFX_ERR_UNKNOWN is returned when HAVC PREENC calls MFXVideoCORE_SyncOperation() in 1toN process 

### ISSUE THREAD

**Issue by waterflag0614** [Intel-Media-SDK/MediaSDK#603]
running 1toN pipeline as following:
Input 1080i -->decoder-->h264 fei encoder1-->output1
                                      -->h264 fei encoder2-->output2
                                      -->h264 fei encoder2-->output3

issue in libmfxhw64.so:
When VideoENC_PREENC::QueryStatus() checks field0 and field1 hanle result by calling VAAPIFEIPREENCEncoder::QueryStatus(field0) and VAAPIFEIPREENCEncoder::QueryStatus(field1).
Field0 surfacc is ready(VASurfaceReady), calling m_statFeedbackCache.erase() to erase vasurface. Field1 is rendering(VASurfaceRendering), returns MFX_WRN_DEVICE_BUSY.
Call VideoENC_PREENC::QueryStatus() again to check field0 and field1 hanle result.
Field0 surfacc is ready(VASurfaceReady), calling m_statFeedbackCache.erase() to erase vasurface.
When check field1, m_statFeedbackCache is NULL, return MFX_ERR_UNKNOWN.
"MFX_CHECK(indxSurf != m_statFeedbackCache.size(), MFX_ERR_UNKNOWN);"

**Comment by dmitryermilov** [comment]
@mgonchar , can you please look at this?

**Comment by mgonchar** [comment]
Sorry for late response. @waterflag0614 could you clarify what is hiding beneath h264 fei encoder 1-3. Is it just FEI ENCODE ? Looks like not, since you are talking about PreENC's functions. From description it sounds to me like some concurrency issue, I would look to the code. But additional description/reproducer will be helpful
