### ISSUE TITLE
Remove contrib/SafeStringStaticLibrary

### ISSUE THREAD

**Issue by chivakker** [Intel-Media-SDK/MediaSDK#705]
Can this project remove that library?

**Comment by dvrogozh** [comment]
As of now contrib/SafeStringStaticLibrary is completely removed from the project. Here are the important notes around this topic:
1. https://github.com/Intel-Media-SDK/MediaSDK/releases/tag/intel-mediasdk-18.3.0 release will get an update (18.3.1) to address this issue. Mostly mediasdk library used memcpy_s from the safec library - these usages will be changed to tiny self-implemented wrapper around memcpy.  As of now the update is under validation, see changes in https://github.com/Intel-Media-SDK/MediaSDK/commits/intel-mediasdk-18.3 release branch.
2. master branch also got safec library dropped via memcpy_s wrapper. However, we made a second step here reviewing and fixing all the places where memcpy_s was used: we used operator= or std::copy where appropriate (self-written wrapper for memcpy_s was dropeed in https://github.com/Intel-Media-SDK/MediaSDK/commit/20a2ecff395d9f5b215a3d04bce9f425561918ba). This will be available in Q4 release.

I believe that as of now mediasdk library is done from the perspective of dropping safec library and immediate follow ups around this topic.

I should note that while mediasdk samples did not use safec library, we believe that we still need to perform samples cleanup from wrappers around standard operations. This work is not done yet, we are scoping it at the moment. Community help is very much welcomed.

I believe the current issue can be now closed. Please, reopen if you think otherwise.
