### ISSUE TITLE
Clang won't build mfx_dispatch_test

### ISSUE THREAD

**Issue by vshampor** [Intel-Media-SDK/MediaSDK#839]
See, for example:
http://mediasdk.intel.com/buildbot/#/builders/10/builds/1814

Apparently Clang, in contrast with GCC, does not allow one extern "C" function to shadow another, the mechanics that we use heavily in mfx_dispatch_test. 

Who is in the wrong here - GCC or Clang? Have we, in fact, been using undefined behavior for our own purposes?

**Comment by dvrogozh** [comment]
clang says this:
```
/localdisk/bb/worker/build-clang-6_0/build_dir/repos_forked/MediaSDK/tests/mfx_dispatch/linux/mfx_dispatch_test_main.cpp:50:12: error: redefinition of 'fgets'
    char * fgets(char* out, int n, FILE* fd)
           ^
/usr/include/x86_64-linux-gnu/bits/stdio2.h:252:1: note: previous definition is here
fgets (char *__restrict __s, int __n, FILE *__restrict __stream)
```
Pay attention that it does not say anything about dlopen/dlsym/dlclose. Why? Answer is pretty simple: because it does not see standard definition. And it saw it for fgets. Different compilers may have slightly different trees of include files... Thus such errors are possible.

So, we do not use any undefined behavior, but we need to be careful with hooking standard functions. I believe we better put them somewhere separate (separate file) and take care to have minimal set of include files avoiding standard headers as much as possible + write a note that this should be considered in support.

@vshampor : can you, please, do?

**Comment by vshampor** [comment]
Compiles well if the -D_FORTIFY_SOURCE=2 option is removed from the compiler flags. This option adds more checks for high-risk functions like fgets via adding a new fgets definition directly in the header which also calls some additional *_chk functions, which causes the problem.

**Comment by vshampor** [comment]
Separating fgets definitions into a separate CPP file won't work easily, since fgets signature has pointers to `FILE` struct, which is defined in the same stdio.h we try to avoid. There is no simple way to bring the FILE struct into our code; also, it would cause some unwanted licensing trouble. 

Instead, will remove the -D_FORTIFY_SOURCE macro from the flag list for the mfx_dispatch_test target.
