### ISSUE TITLE
If monitor not connected then less performance

### ISSUE THREAD

**Issue by devalexqt** [Intel-Media-SDK/MediaSDK#862]
Then reboot PC without monitor to be connected and run command over shh (like on server) then I get less fps (converting speed).
Build with instructions: https://gist.github.com/Brainiarc7/4f831867f8e55d35cbcb527e15f9f116
 
Trsted on i7- 6700 and on i7- 8700 CPU on Ubuntu 18.04 with ffmpeg.

`
ffmpeg -hwaccel qsv -c:v h264_qsv  -i 720p.mp4 -c:v h264_qsv -preset 7 -b:v 6M -vf scale_qsv=1920:1080 -an -y h264.mp4
`
Monitor connected : fps: 330fps
Monitor not connected: 250fps

**Comment by eero-t** [comment]
Is it enough to just turn monitor off with DPMS to see the perf drop:
`xset dpms force off`

And which version of DMC (display controller firmware) you have on each of those devices:
`dmesg | grep DMC`
?

There was a problem with older DMC versions, they went to some low power mode when display wasn't connected, so that it affected also media engine, not just display engine.

I didn't have time to check your exact use-case, but with the use-cases for which I have data, performance is nowadays same with monitor turned on and off (with DPMS) when using up to date DMC firmware e.g. on these devices:
* i5-6600K: i915/skl_dmc_ver1_27.bin (v1.27)
* i7-7567U: i915/kbl_dmc_ver1_04.bin (v1.4)
* i7-8700: i915/kbl_dmc_ver1_04.bin (v1.4)

(These were tested with git builds of kernel and MediaSDK & its dependencies, using "sample_multi_transcode" from MediaSDK.)

**Comment by devalexqt** [comment]
i7-8700:
`[    6.209663] [drm] Finished loading DMC firmware i915/kbl_dmc_ver1_01.bin (v1.1)
`
i7-6700:
`[    1.572430] [drm] Finished loading DMC firmware i915/skl_dmc_ver1_26.bin (v1.26)`

On 8700 I have't X session at all because its server and cant run "xset dpms force off".

On 6700 after run "xset dpms force off" screen blank and come back to normal in couple of seconds. So can't detect performance.

Note: I see fps drop from 310 to 200 fps (this is 33%!!!), without monitor, only if I use overlay_qsv filter in ffmpeg(with and without monitor), but if I don't include overlay_qsv filter then fps drop is not so big 5-10%.

**Comment by devalexqt** [comment]
6700: 
new kernel: 4.18
`[    1.132263] [drm] Finished loading DMC firmware i915/skl_dmc_ver1_**27**.bin (v1.27)`

8700: 
new kernel
` 4.19.0-041900 `
`[    1.927004] [drm] Finished loading DMC firmware i915/kbl_dmc_ver1_04.bin (v1.4)`

And fps is Good! ( think, about, 5% fps).
So, after update to new kernel, looks like problem is gone, but I need more test to complete.

**Comment by devalexqt** [comment]
Confirm, all looks the same fps.
Thanks!

**Comment by Brainiarc7** [comment]
I can reproduce your results with older kernels (4.17.x vs the latest mainline).

**Comment by eero-t** [comment]
> Note: I see fps drop from 310 to 200 fps (this is 33%!!!), without monitor, only if I use overlay_qsv filter in ffmpeg(with and without monitor), but if I don't include overlay_qsv filter then fps drop is not so big 5-10%.

My assumption: this is just because extra filter will cause higher media engine utilization (*), so the drop in engine frequency affects the performance of the whole thing more.

(*) If you're using just one stream and not doing anything extra, media engine won't be fully utilized:
https://github.com/Intel-Media-SDK/MediaSDK/wiki/MFE-Overview

Note: "intel_gpu_top" tool from intel-gpu-tools project shows you utilization of media engines, but you need at least kernel v4.16 and build it from git:
https://cgit.freedesktop.org/xorg/app/intel-gpu-tools/

intel-gpu-tools package v1.22 in Ubuntu is too old to include media utilization info in intel_gpu_top.   v1.23 is new enough to include the required change:
https://cgit.freedesktop.org/xorg/app/intel-gpu-tools/commit/?id=63f0bf3d50b70f011b9d600a1a4bc1a1c7720654

> So, after update to new kernel, looks like problem is gone, but I need more test to complete.

Great!

Looking at the Ubuntu 18.04 LTS point release update schedule:
https://wiki.ubuntu.com/Kernel/Support?action=AttachFile&do=get&target=18.04.x+Ubuntu+Kernel+Support+Schedule.svg

18.04 will get (HWE) kernel from 18.10 around Feb 2019.  18.10 has v4.18 kernel which is new enough to have the DMC fix.  Even v4.16 kernel might be new enough.

(Kernel / DMC firmware issue was noticed last year, and I think fixed firmware came at end of 2017 or start of 2018, which was too late for 18.04 Ubuntu kernel version freeze.)

Btw. You might want to file bug for Ubuntu 18.04 to let them know about the issue in their current kernel version. :-)

**Comment by eero-t** [comment]
> I can reproduce your results with older kernels (4.17.x vs the latest mainline).

Even v4.17 has bad performance?

If yes, on which machine this is:
`grep name /proc/cpuinfo | uniq`

And which DMC version it uses:
`dmesg | grep DMC`
?

**Comment by devalexqt** [comment]
I use intel-gpu-tools 1.22-1 from ubuntu repo and it not truly show video engine usage. But after I compiled it from git intel_gpu_tool start showing: Render, Video and VideoEnhance usage and this is very good! But new version of tool don't have any options to write log to the file or stdio (old version have "-o" option) and this is critical for my server, because I need parse output from intel_gpu_tool and emit it via socket.io to web page for monitoring server usage. Can You send request for "Write log to file/stdio" case?

For my i7-6700 with kernel:
`4.17.0-041700-generic #201806041953 SMP Mon Jun 4 19:55:25 UTC 2018`
 I have: (may be updated version of DMC is left from v4.18 kernel, because I downgraded kernel for test)

`[    1.966228] [drm] Finished loading DMC firmware i915/skl_dmc_ver1_27.bin (v1.27)` 

And no fps drop. Looks good!

**Comment by dvrogozh** [comment]
As an alternative to intel-gpu-tools you can use:
`perf stat -a -e i915/bcs0-busy/,i915/rcs0-busy/,i915/vcs0-busy/,i915/vcs1-busy/,i915/vecs0-busy/ <workload.sh>
`
This will dump to stdout total statistics per-engine (us each engine was doing something). You can play with -I 100 option if you need statistics dumped each 100 something. Pay attention on `-a` since i915 statistics is global.

**Comment by dvrogozh** [comment]
Pay attention that up-to-date DMC FW is merely a prerequisite. The fix for the performance is not in the DMC, but in i915 driver. Here it is: https://patchwork.freedesktop.org/patch/191822/. If I remember correctly it is available since kernel 4.16.

**Comment by devalexqt** [comment]
Yes, "perf" working, after rebuild for new kernel, and need to play with correct parse it to monitoring script, but will be cool if intel_gpu_top can do it too.

**Comment by devalexqt** [comment]
Also, where I can get explain description of every parameters, for example i915/bcs0-busy ?

**Comment by eero-t** [comment]
> will be cool if intel_gpu_top can do it too

You can file intel-gpu-tools feature requests to upstream bug tracker (select component "DRM/Intel"):
https://bugs.freedesktop.org/enter_bug.cgi?product=DRI

> where I can get explain description of every parameters, for example i915/bcs0-busy

You can get list of them with "perf list", but I think that for explanation of them, you really need to look into kernel commits and discussion on them, like this:
https://patchwork.kernel.org/patch/9876717/

In general, the busy counter is about how much of the time kernel thinks the media engine to be busy (= can't feed it new stuff), not the utilization percentage of given HW (which has multiple aspects).

**Comment by devalexqt** [comment]
Thanks!
