### ISSUE TITLE
MediaSDK performance lower than MediaServerStudioProfessionalEvaluation2017R3

### ISSUE THREAD

**Issue by YaboWei** [Intel-Media-SDK/MediaSDK#95]
Hi,
I test the performance between MediaSDK and MediaServerStudioProfessionalEvaluation2017R3:

# result

  | MediaSDK | MSS2017R3
-- | -- | --
enc | 0m29.179s | 0m21.813s
dec | fps: 516.188 | fps: 676.469
with ffmpeg | fps=218 | fps=262

# enc (run multi times to avoid I/O limit)
## MediaSDK
time __cmake/intel64.make.release/__bin/release/sample_encode h264 -i ~/samples/assassin_st4_1080p30fps.flv.yuv -o out.264 -w 1920 -h 1080 -hw
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
Encoding Sample Version 8.2.25.

Input file format	YUV420
Output video		AVC 
Source picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Destination picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Frame rate	30.00
Bit rate(Kbps)	3757
Gop size	0
Ref dist	0
Ref number	0
Idr Interval	0
Target usage	balanced
Memory type	system
Media SDK impl		hw
Media SDK version	1.25

Processing started
Frame number: 5797

Processing finished

real	0m29.179s
user	0m20.372s
sys	0m9.306s

## MediaServerStudioProfessionalEvaluation2017R3

time ./__cmake/intel64.make.release/__bin/release/sample_encode h264 -i ~/samples/assassin_st4_1080p30fps.yuv -o out.264 -w 1920 -h 1080 -hw
libva info: VA-API version 0.99.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_0_32
libva info: va_openDriver() returns 0
Encoding Sample Version 0.0.000.0000

Input file format	YUV420
Output video		AVC 
Source picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Destination picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Frame rate	30.00
Bit rate(Kbps)	3757
Gop size	0
Ref dist	0
Ref number	0
Idr Interval	0
Target usage	balanced
Memory type	system
Media SDK impl		hw
Media SDK version	1.23

Processing started
Frame number: 5797

Processing finished

real	0m21.813s
user	0m10.992s
sys	0m4.827s

# dec
## MediaSDK
pretending that aspect ratio is 1:1
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
Decoding Sample Version 8.2.25.

Input video	AVC 
Output format	NV12
Input:
  Resolution	1920x1088
  Crop X,Y,W,H	0,0,0,0
Output:
  Resolution	1920x1088
Frame rate	30.00
Memory type		system
MediaSDK impl		hw
MediaSDK version	1.25

Decoding started
Frame number: 5797, fps: 516.188, fread_fps: 0.000, fwrite_fps: 0.000
Decoding finished

## MediaServerStudioProfessionalEvaluation2017R3
pretending that aspect ratio is 1:1
libva info: VA-API version 0.99.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_0_32
libva info: va_openDriver() returns 0
Decoding Sample Version 0.0.000.0000

Input video	AVC 
Output format	NV12
Input:
  Resolution	1920x1088
  Crop X,Y,W,H	0,0,0,0
Output:
  Resolution	1920x1088
Frame rate	30.00
Memory type		system
MediaSDK impl		hw
MediaSDK version	1.23

Decoding started
Frame number: 5797, fps: 676.469, fread_fps: 0.000, fwrite_fps: 0.000
Decoding finished

# transcode with ffmpeg
https://github.com/Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins.git
branch intel_plugins-3.3.1
command ./ffmpeg -hwaccel qsv -c:v h264_qsv -i 1080p30fps.flv -c:v h264_qsv -profile:v high -preset medium -b:v 3000k -maxrate:v 6000k -bufsize:v 6000k -look_ahead 1 -look_ahead_depth 20 -g 50 -an -f null -

## MediaSDK
frame= 5797 fps=218
## MediaServerStudioProfessionalEvaluation2017R3
frame= 5797 fps=262

**Comment by dvrogozh** [comment]
Hi,

There could be few reasons to that. Need to see details on your configuration and open source build procedure to advice. There are few major things for initial check:
1. On which HW are you running?
2. Which kernel are you using to run open source build of mediasdk?
3. Which user mode driver are you using to run open source build of mediasdk? Are you using this one: https://github.com/intel/media-driver or https://github.com/intel/intel-vaapi-driver?

Assuming that you are trying to evaluate MSS 2017R3 against full open source stack which is:
- mediasdk from this github repository 
- https://github.com/intel/media-driver
- Linux kernel 4.14 or later

I would suggest to check one of the following 2 reasons why you may see lower performance:
1. If you run on Gen9+ in headless mode, then you may step into the https://bugs.freedesktop.org/show_bug.cgi?id=100572. Issue is fixed in 4.16 kernel and in SKL DMC FW v1.27. You may try to update SKL DMC FW to v1.27 and apply the following patches over kernel (if you are under 4.14):
1.1. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/commit/?id=39ccc9852e2b46964c9c44eba52db57413ba6d27
1.2 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/commit/?id=b68763741aa29f2541c7ca58bcb0c2bb6cb5f449
2. If you built open source stack on the same system _after_ MSS 2017R3 and you did not fully uninstall it, then media-driver build could potentially fetch "intel_mocs_table.h" include file from MSS and build driver with the extended MOCS (GPU objects caching) settings. If you then run such a driver under 4.14 kernel it will give significantly lower performance since i915 KMD will not have required MOCS settings. You can check which build path is chosen in media-driver here: https://github.com/intel/gmmlib/blob/master/Source/GmmLib/CachePolicy/GmmGen9CachePolicy.cpp#L27. If HAVE_MESA_MOCS is defined you are in trouble.

Regards,
Dmitry.

**Comment by lp35** [comment]
Hi,

I see you are comparing results with ffmpeg. I would like to ask a simple question concerning the ffmpeg build.

IMHO, ffmpeg "plugin" is not clear. Is it really a new codec in libavcodec, different from the one provided in ffmpeg official build? Or is it simply a version that is more up to date with the upstream IntelMedia sdk? Is this version tightened with a specific version of MSDK?

You are also talking about a R3.4.2 version, that is not visible on the Intel ffmpeg version so far (I see only v. 3.4.1). Have you rebased?

Thank you for your help.

**Comment by onabiull** [comment]
@YaboWei I believe most performance-related patches landed in latest kernels. Could you please check w/kernel 5.3 if this still actual?
