### ISSUE TITLE
how to build sample on ubuntu14.04

### ISSUE THREAD

**Issue by ahuer2435** [Intel-Media-SDK/MediaSDK#993]
I install Media SDK following: https://github.com/Intel-Media-SDK/MediaSDK/wiki/Build-Media-SDK-on-Ubuntu.
After that, I want build sample . I follow: https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/samples/Media_Samples_Guide_Linux.pdf, but I could not find build.pl in sample dir.

**Comment by onabiull** [comment]
If you cloned git repo, then regular cmake is all that you need. By default samples build enabled, so 
`mkdir build && cd build
cmake ..
make -j4`
should be enough. cmake call would produce a table with build options, so you can alter them at will.

Since Q3.1 release samples in MediaStack.tar.gz also built w/o perl wrapper.
